news_website/blog/urls.py
from django.urls import path, re_path
from .views import post_list, post_detail

app_name = "blog"

urlpatterns = [
    path("", post_list, name="post_list"),
    path("category/<slug:category_slug>/", post_list, name="category_list"),
    path("author/<int:author_pk>/", post_list, name="author_list"),
    re_path(
        r"^post/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]{1,2})/(?P<slug>[-\w]+)/$",
        post_detail,
        name="post_detail",
    ),
    re_path(
        r"^post/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]{1,2})/(?P<slug>[-\w]+)/comment/edit/(?P<comment_id>[0-9]+)/$",
        post_detail,
        name="comment_edit",
    ),
    re_path(r"^tag/(?P<tag_slug>[-\w]+)/", post_list, name="tag_list"),
]

news_website/news_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls", namespace="blog")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("cadmin/", include("cadmin.urls", namespace="cadmin")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news_website/blog/models.py
from django.db import models

# from django.contrib.auth.models import User
from accounts.models import User
from django.utils import timezone
from django.urls import reverse
from extensions.utils import jalali_converter
from taggit.managers import TaggableManager


# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=50, verbose_name="عنوان دسته بندی")
    slug = models.SlugField(max_length=300, unique=True, allow_unicode=True)
    is_visible = models.BooleanField(default=True)
    position = models.IntegerField()

    class Meta:
        ordering = ("position",)
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:category_list", kwargs={"category_slug": self.slug})


class Post(models.Model):
    STATUS_CHOICES = (("draft", "پیشنویس"), ("published", "منتشر شده"))
    title = models.CharField(max_length=250, verbose_name="عنوان")
    category = models.ManyToManyField(Category, verbose_name="دسته بندی")
    thumbnail = models.ImageField(
        upload_to="image", null=True, blank=True, verbose_name="تصویر"
    )
    slug = models.SlugField(max_length=300, unique=True, allow_unicode=True)
    body = models.TextField(verbose_name="متن", null=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="blog_posts",
        verbose_name="نویسنده",
    )
    publish = models.DateTimeField(default=timezone.now, verbose_name="زمان انتشار")
    created = models.DateTimeField(auto_now_add=timezone.now, verbose_name="زمان ایجاد")
    updated = models.DateTimeField(auto_now=timezone.now)
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default="draft",
        verbose_name="وضعیت انتشار",
    )
    tags = TaggableManager()

    class Meta:
        ordering = ("-publish",)
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"

    def __str__(self):
        return self.title

    def get_category(self):
        return ", ".join([cat.title for cat in self.category.all()])

    get_category.short_description = "دسته بندی"

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            kwargs={
                "year": self.publish.year,
                "month": self.publish.month,
                "day": self.publish.day,
                "slug": self.slug,
            },
        )

    def jpublish(self):
        return jalali_converter(self.publish)

    def save(self, *args, **kwargs):
        slug = ""
        for char in self.title:
            if char.isalpha():
                slug += char
            elif char == " ":
                slug += "-"
        self.slug = slug
        super().save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ["-created_on"]
        verbose_name = "نظر"
        verbose_name_plural = "نظرات"

    def __str__(self):
        return "Comment {} by {}".format(self.body, self.name)

news_website/blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

news_website/blog/views.py
from django.shortcuts import render
from .models import Post, Category, Comment
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from .forms import CommentForm
from taggit.models import Tag
from django.db.models import Count

# Create your views here.


def post_list(request, category_slug=None, author_pk=None, tag_slug=None):
    posts = Post.objects.filter(status="published")
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        posts = posts.filter(category=category)

    if author_pk:
        user = get_object_or_404(User, pk=author_pk)
        posts = posts.filter(author=user)

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags=tag)
    return render(request, "blog/index.html", {"posts": posts})


def post_detail(request, year, month, day, slug, comment_id=None):
    # post = Post.objects.get(id = pk)
    post = get_object_or_404(
        Post,
        publish__year=year,
        publish__month=month,
        publish__day=day,
        slug=slug,
        status="published",
    )
    tags = post.tags.all()
    comments = post.comments.filter(active=True)
    post_tags_id = post.tags.values_list("id", flat=True)
    similar_posts = Post.objects.filter(
        status="published", tags__in=post_tags_id
    ).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
        "-same_tags", "-publish"
    )[:5]

    if request.method == "POST":
        if comment_id:
            comment = get_object_or_404(Comment, id=comment_id)
            comment_form = CommentForm(instance=comment, data=request.POST)
        else:
            comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.active = False
            comment.save()
    else:
        comment_form = CommentForm()
        if comment_id:
            comment = get_object_or_404(Comment, id=comment_id)
            comment_form = CommentForm(instance=comment)

    return render(
        request,
        "blog/single.html",
        {
            "post": post,
            "comments": comments,
            "comment_form": comment_form,
            "tags": tags,
            "similar_posts": similar_posts,
        },
    )

news_website/templates/blog/index.html
{% extends "blog/base.html" %}
{% block content %}
<div class="col-lg-9 col-md-12 col-sm-12 col-xs-12">
    <div class="page-wrapper">
    {% for post in posts %}
        <div class="blog-list clearfix">
            <div class="blog-box row">
                <div class="col-md-4">
                    <div class="post-media">
                        <a href="{{post.get_absolute_url}}" title="">
                            <img src="{% if post.thumbnail %}{{post.thumbnail.url}}{% endif %}" alt="" class="img-fluid">
                            <div class="hovereffect"></div>
                        </a>
                    </div><!-- end media -->
                </div><!-- end col -->

                <div class="blog-meta big-meta col-md-8">
                    <h4><a href="{{post.get_absolute_url}}" title="">{{post.title}}</a></h4>
                    <p>{{post.body|truncatewords:30}}</p>
                    <small class="firstsmall">
                        {% for cat in post.category.all %}
                        <a class="bg-orange" href='{{cat.get_absolute_url}}' title="">
                            {{cat.title}}</a>
                        {% endfor %}
                    </small>
                    <small><a href="tech-single.html" title="">{{post.jpublish}}</a></small>
                    <small><a href='{% url "blog:author_list" post.author.pk %}' title="">{{post.author.get_full_name}}</a></small>
                    <small><a href="tech-single.html" title=""><i class="fa fa-eye"></i> 1114</a></small>
                </div><!-- end meta -->
            </div><!-- end blog-box -->
            <hr class="invis">
        </div><!-- end blog-list -->
    {% endfor %}
    </div><!-- end page-wrapper -->

    <div class="row">
        <div class="col-md-12">
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-start">
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>
        </div><!-- end col -->
    </div><!-- end row -->
</div><!-- end col -->
{% endblock content %}

news_website/templates/blog/single.html
{% extends "blog/base.html" %}
{% block content %}
<div class="col-lg-9 col-md-12 col-sm-12 col-xs-12">
    <div class="page-wrapper">
        <div class="blog-title-area text-center">
            <ol class="breadcrumb hidden-xs-down">
                <li class="breadcrumb-item"><a href='{% url "blog:post_list" %}'>خانه</a></li>
                <li class="breadcrumb-item active">{{post.title}}</li>
            </ol>

            {% for cat in post.category.all %}
            <span class="color-orange"><a href="{{cat.get_absolute_url}}" title="">{{cat.title}}</a></span>
            {% endfor %}

            <h3>{{post.title}}</h3>

            <div class="blog-meta big-meta">
                <small><a href="tech-single.html" title="">{{post.jpublish}}</a></small>
                <small><a href="tech-author.html" title="">{{post.author.get_full_name}}</a></small>
                <small><a href="#" title=""><i class="fa fa-eye"></i> 2344</a></small>
            </div><!-- end meta -->

            <div class="post-sharing">
                <ul class="list-inline">
                    <li><a href="#" class="fb-button btn btn-primary"><i class="fa fa-facebook"></i> <span class="down-mobile">Share on Facebook</span></a></li>
                    <li><a href="#" class="tw-button btn btn-primary"><i class="fa fa-twitter"></i> <span class="down-mobile">Tweet on Twitter</span></a></li>
                    <li><a href="#" class="gp-button btn btn-primary"><i class="fa fa-google-plus"></i></a></li>
                </ul>
            </div><!-- end post-sharing -->
        </div><!-- end title -->

        <div class="single-post-media">
            <img src="{% if post.thumbnail %}{{post.thumbnail.url}}{% endif %}" alt="" class="img-fluid">
        </div><!-- end media -->

        <div class="blog-content">  
            <div class="pp">
                <p>{{post.body}}</p>
            </div><!-- end pp -->

        </div><!-- end content -->

        <div class="blog-title-area">
            <div class="tag-cloud-single">
                <span>برچسب ها</span>
                {% for tag in tags %}
                <small><a href='{% url "blog:tag_list" tag.slug %}' title="">{{tag.name}}</a></small>
                {% endfor %}
                
                </div><!-- end meta -->

            <div class="post-sharing">
                <ul class="list-inline">
                    <li><a href="#" class="fb-button btn btn-primary"><i class="fa fa-facebook"></i> <span class="down-mobile">Share on Facebook</span></a></li>
                    <li><a href="#" class="tw-button btn btn-primary"><i class="fa fa-twitter"></i> <span class="down-mobile">Tweet on Twitter</span></a></li>
                    <li><a href="#" class="gp-button btn btn-primary"><i class="fa fa-google-plus"></i></a></li>
                </ul>
            </div><!-- end post-sharing -->
        </div><!-- end title -->

        <div class="row">
            <div class="col-lg-12">
                <div class="banner-spot clearfix">
                    <div class="banner-img">
                        <img src="upload/banner_01.jpg" alt="" class="img-fluid">
                    </div><!-- end banner-img -->
                </div><!-- end banner -->
            </div><!-- end col -->
        </div><!-- end row -->

        <hr class="invis1">

        <div class="custombox prevnextpost clearfix">
            <div class="row">
                <div class="col-lg-6">
                    <div class="blog-list-widget">
                        <div class="list-group">
                            <a href="tech-single.html" class="list-group-item list-group-item-action flex-column align-items-start">
                                <div class="w-100 justify-content-between text-right">
                                    <img src="upload/tech_menu_19.jpg" alt="" class="img-fluid float-right">
                                    <h5 class="mb-1">5 Beautiful buildings you need to before dying</h5>
                                    <small>Prev Post</small>
                                </div>
                            </a>
                        </div>
                    </div>
                </div><!-- end col -->

                <div class="col-lg-6">
                    <div class="blog-list-widget">
                        <div class="list-group">
                            <a href="tech-single.html" class="list-group-item list-group-item-action flex-column align-items-start">
                                <div class="w-100 justify-content-between">
                                    <img src="upload/tech_menu_20.jpg" alt="" class="img-fluid float-left">
                                    <h5 class="mb-1">Let's make an introduction to the glorious world of history</h5>
                                    <small>Next Post</small>
                                </div>
                            </a>
                        </div>
                    </div>
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end author-box -->

        <hr class="invis1">

        <div class="custombox authorbox clearfix">
            <h4 class="small-title">About author</h4>
            <div class="row">
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                    <img src="upload/author.jpg" alt="" class="img-fluid rounded-circle"> 
                </div><!-- end col -->

                <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
                    <h4><a href="#">Jessica</a></h4>
                    <p>Quisque sed tristique felis. Lorem <a href="#">visit my website</a> amet, consectetur adipiscing elit. Phasellus quis mi auctor, tincidunt nisl eget, finibus odio. Duis tempus elit quis risus congue feugiat. Thanks for stop Tech Blog!</p>

                    <div class="topsocial">
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title="Facebook"><i class="fa fa-facebook"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title="Youtube"><i class="fa fa-youtube"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title="Pinterest"><i class="fa fa-pinterest"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title="Twitter"><i class="fa fa-twitter"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title="Instagram"><i class="fa fa-instagram"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title="Website"><i class="fa fa-link"></i></a>
                    </div><!-- end social -->

                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end author-box -->

        <hr class="invis1">

        <div class="custombox clearfix">
            <h4 class="small-title">شاید بپسندید</h4>
            
                {% for smilar_post in similar_posts %}
                <div class="row">
                <div class="col-lg-6">
                    <div class="blog-box">
                        <div class="post-media">
                            <a href= '{{smilar_post.get_absolute_url}}' title="">
                                <img src="{{smilar_post.thumbnail.url}}" alt="" class="img-fluid">
                                <div class="hovereffect">
                                    <span class=""></span>
                                </div><!-- end hover -->
                            </a>
                        </div><!-- end media -->
                        <div class="blog-meta">
                            <h4><a href='{{smilar_post.get_absolute_url}}' title="">{{smilar_post.title}}</a></h4>
                            <small><a href='{{smilar_post.get_absolute_url}}' title="">{{smilar_post.get_category}}</a></small>
                            <small><a href='{{smilar_post.get_absolute_url}}' title="">{{smilar_post.jpublish}}</a></small>
                        </div><!-- end meta -->
                    </div><!-- end blog-box -->
                </div><!-- end col -->  
                </div><!-- end row -->
                {% endfor %}
                
        </div><!-- end custom-box -->

        <hr class="invis1">

        <div class="custombox clearfix">
            {% with comments.count as Total_Comments %}
            <h4 class="small-title">{{Total_Comments}} نظر</h4>
            {% endwith %}
            <div class="row">
                <div class="col-lg-12">
                    <div class="comments-list">
                        {% for comment in comments %}
                        <div class="media">
                            <a class="media-left" href="#">
                                <img src="upload/author.jpg" alt="" class="rounded-circle">
                            </a>
                            <div class="media-body">
                                <h4 class="media-heading user_name">{{comment.name}} <small>5 days ago</small></h4>
                                <p>{{comment.body}}</p>
                                <a href={% url "blog:comment_edit" post.publish.year post.publish.month post.publish.day post.slug comment.id %} class="btn btn-primary btn-sm">ویرایش</a>
                            </div>
                        </div>
                        {% endfor %}


                    </div>
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end custom-box -->

        <hr class="invis1">

        <div class="custombox clearfix">
            <h4 class="small-title">Leave a Reply</h4>
            <div class="row">
                <div class="col-lg-12">
                    <form class="form-wrapper" method = 'post'>
                        <input type="text" name= 'name'  class="form-control" placeholder="نام" value = '{{comment_form.name.value}}'>
                        <input type="text" name= 'email' class="form-control" placeholder="ایمیل" value = '{{comment_form.email.value}}'>
                        <textarea class="form-control" name= 'body' placeholder="نظر">{{comment_form.body.value}}</textarea>
                        <input type="submit" class="btn btn-primary" value ='ارسال'>
                        {% csrf_token %}
                        
                    </form>

                </div>
            </div>
        </div>
    </div><!-- end page-wrapper -->
</div><!-- end col -->
{% endblock content %}